symfony/src/Entity/Profile.php
<?php

namespace App\Entity;

use App\Repository\ProfileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: ProfileRepository::class)]
#[ORM\Index(columns: ['slug'], name: 'profile__slug__inx')]
class Profile
{
    use TimestampableEntity;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Gedmo\Slug(fields: ['first_name', 'last_name', 'surname'])]
    private string $slug;

    #[ORM\Column(length: 255)]
    private string $first_name;

    #[ORM\Column(length: 255)]
    private string $last_name;

    #[ORM\Column(length: 255)]
    private ?string $surname = null;

    #[ORM\Column(length: 255)]
    private string $email;

    #[ORM\Column(length: 255)]
    private string $phone;

    #[ORM\Column(length: 255)]
    private string $experience;

    #[ORM\ManyToMany(targetEntity: Service::class, mappedBy: 'profile')]
    private Collection $services;

    public function __construct()
    {
        $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getExperience(): ?string
    {
        return $this->experience;
    }

    public function setExperience(string $experience): static
    {
        $this->experience = $experience;

        return $this;
    }

    /**
     * @return Collection<int, Service>
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): static
    {
        if (!$this->services->contains($service)) {
            $this->services->add($service);
            $service->addProfile($this);
        }

        return $this;
    }

    public function removeService(Service $service): static
    {
        if ($this->services->removeElement($service)) {
            $service->removeProfile($this);
        }

        return $this;
    }

    public function toArray(): array
    {
        return [
            'slug' => $this->getSlug(),
            'first_name' => $this->getFirstName(),
            'last_name' => $this->getLastName(),
            'surname' => $this->getSurname(),
            'email' => $this->getEmail(),
            'phone' => $this->getPhone(),
            'experience' => $this->getExperience(),
        ];
    }
}

symfony/templates/frontend/pages/index.html.twig
{% extends 'frontend/layout/base.html.twig' %}

{% block content %}
    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

                <div class="container">
                    <div class="carousel-caption text-start">
                        <h1>Example headline.</h1>
                        <p>Some representative placeholder content for the first slide of the carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

                <div class="container">
                    <div class="carousel-caption">
                        <h1>Another example headline.</h1>
                        <p>Some representative placeholder content for the second slide of the carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"></rect></svg>

                <div class="container">
                    <div class="carousel-caption text-end">
                        <h1>One more for good measure.</h1>
                        <p>Some representative placeholder content for the third slide of this carousel.</p>
                        <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="container marketing">
        <div class="row">
                {% for serviceL1 in services %}
                    <div class="col-lg-4 text-start" >
                        <div class="text-start">
                            <h2>{{ serviceL1.name }}</h2>
                            {% if serviceL1.children %}
                                {% for service in serviceL1.children | slice(1, 10) %}
                                    {% if location %}
                                        <a class="services-list-column-item"
                                           href="{{ path('service.location.profiles', {location: location.slug, slug: service.slug}) }}">
                                            {{ service.name }}
                                        </a><br>
                                    {% else %}
                                        <a class="services-list-column-item"
                                           href="{{ path('service.profiles', {slug: service.slug}) }}">
                                            {{ service.name }}
                                        </a><br>
                                    {% endif %}
                                {% endfor %}

                                {% if serviceL1.children|length > 10 %}
                                    <br><p><a class="btn btn-secondary" href="">Все услуги »</a></p>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        </div>
        <hr class="featurette-divider">
    </div>
{% endblock %}

symfony/templates/frontend/pages/profile.html.twig
{% extends 'frontend/layout/base.html.twig' %}
{% block content %}
    <h1>#{{ profile.id }} {{ profile.firstName }} {{ profile.surname }}</h1> <br>

{% endblock %}

symfony/templates/frontend/pages/service.html.twig
{% extends 'frontend/layout/base.html.twig' %}
{% block content %}
    <div class="profiles-list">
        {% for profile in profiles %}
                <a href="{{ path('profile.detail', {slug: profile.slug}) }}">{{ profile.id }} -- {{ profile.firstName }} {{ profile.surname }}</a> <br>
        {% endfor %}
    </div>
{% endblock %}